/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.melissadata;

public class mdGeoJavaWrapperJNI {
//static{
//try{ System.loadLibrary("mdGeoJavaWrapper");}
//catch(UnsatisfiedLinkError ule){
//System.out.println(ule);
//System.out.println("java.library.path = " + System.getProperty("java.library.path"));}}
  public final static native int mdGeo_ErrorNone_get();
  public final static native int mdGeo_Local_get();
  public final static native int mdGeo_Auto_get();
  public final static native int mdGeo_FCM_LTR_AUTO_NONAUTO_get();
  public final static native int mdGeo_FCM_POSTCARD_AUTO_NONAUTO_get();
  public final static native int mdGeo_FCM_FLAT_COTRAY_get();
  public final static native int mdGeo_STD_LTR_ECRRT_AUTO_NONAUTO_get();
  public final static native int mdGeo_STD_FLAT_ECRRT_COSACK_get();
  public final static native int mdGeo_RESIDUALS_LEFT_get();
  public final static native long new_mdGeo();
  public final static native void delete_mdGeo(long jarg1);
  public final static native void mdGeo_SetPathToGeoCodeDataFiles(long jarg1, mdGeo jarg1_, String jarg2);
  public final static native void mdGeo_SetPathToGeoPointDataFiles(long jarg1, mdGeo jarg1_, String jarg2);
  public final static native void mdGeo_SetPathToGeoCanadaDataFiles(long jarg1, mdGeo jarg1_, String jarg2);
  public final static native boolean mdGeo_SetLicenseString(long jarg1, mdGeo jarg1_, String jarg2);
  public final static native int mdGeo_Initialize(long jarg1, mdGeo jarg1_, String jarg2, String jarg3);
  public final static native int mdGeo_InitializeDataFiles(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetInitializeErrorString(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetBuildNumber(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetDatabaseDate(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetExpirationDate(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetLicenseExpirationDate(long jarg1, mdGeo jarg1_);
  public final static native int mdGeo_GeoCode__SWIG_0(long jarg1, mdGeo jarg1_, String jarg2, String jarg3);
  public final static native int mdGeo_GeoCode__SWIG_1(long jarg1, mdGeo jarg1_, String jarg2);
  public final static native int mdGeo_GeoPoint(long jarg1, mdGeo jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native double mdGeo_ComputeDistance(long jarg1, mdGeo jarg1_, double jarg2, double jarg3, double jarg4, double jarg5);
  public final static native double mdGeo_ComputeBearing(long jarg1, mdGeo jarg1_, double jarg2, double jarg3, double jarg4, double jarg5);
  public final static native String mdGeo_GetErrorCode(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetStatusCode(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetResults(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetLatitude(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetLongitude(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetCensusTract(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetCensusBlock(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetCountyFips(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetCountyName(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetPlaceCode(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetPlaceName(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetTimeZoneCode(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetTimeZone(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetCBSACode(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetCBSATitle(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetCBSALevel(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetCBSADivisionCode(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetCBSADivisionTitle(long jarg1, mdGeo jarg1_);
  public final static native String mdGeo_GetCBSADivisionLevel(long jarg1, mdGeo jarg1_);
}
