/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.melissadata;

public class mdGlobalAddrJavaWrapperJNI {
//static{
//try{ System.loadLibrary("mdGlobalAddrJavaWrapper");}
//catch(UnsatisfiedLinkError ule){
//System.out.println(ule);
//System.out.println("java.library.path = " + System.getProperty("java.library.path"));}
//}
  public final static native int mdGlobalAddr_ErrorNone_get();
  public final static native int mdGlobalAddr_Local_get();
  public final static native int mdGlobalAddr_Auto_get();
  public final static native int mdGlobalAddr_ShortFormat_get();
  public final static native int mdGlobalAddr_ParseSuite_get();
  public final static native int mdGlobalAddr_ConvertAlias_get();
  public final static native int mdGlobalAddr_AutoCompleteSingleSuite_get();
  public final static native int mdGlobalAddr_ResultCodeDescriptionLong_get();
  public final static native long new_mdGlobalAddr();
  public final static native void delete_mdGlobalAddr(long jarg1);
  public final static native boolean mdGlobalAddr_SetLicenseString(long jarg1, mdGlobalAddr jarg1_, String jarg2);
  public final static native void mdGlobalAddr_SetPathToGlobalAddrFiles(long jarg1, mdGlobalAddr jarg1_, String jarg2);
  public final static native int mdGlobalAddr_InitializeDataFiles(long jarg1, mdGlobalAddr jarg1_);
  public final static native void mdGlobalAddr_ClearProperties(long jarg1, mdGlobalAddr jarg1_);
  public final static native boolean mdGlobalAddr_SetInputParameter(long jarg1, mdGlobalAddr jarg1_, String jarg2, String jarg3);
  public final static native int mdGlobalAddr_VerifyAddress(long jarg1, mdGlobalAddr jarg1_);
  public final static native String mdGlobalAddr_GetOutputParameter(long jarg1, mdGlobalAddr jarg1_, String jarg2);
  public final static native String mdGlobalAddr_TransliterateText(long jarg1, mdGlobalAddr jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native String mdGlobalAddr_GetCurrentAtomSet(long jarg1, mdGlobalAddr jarg1_);
  public final static native String mdGlobalAddr_InputsAsAtomSet(long jarg1, mdGlobalAddr jarg1_);
  public final static native String mdGlobalAddr_RightFieldResultsAsAtomSet(long jarg1, mdGlobalAddr jarg1_, String jarg2);
  public final static native String mdGlobalAddr_TokenizerResultsAsAtomSet(long jarg1, mdGlobalAddr jarg1_, String jarg2);
  public final static native String mdGlobalAddr_InputMapperResultsAsAtomSet(long jarg1, mdGlobalAddr jarg1_, String jarg2);
  public final static native String mdGlobalAddr_MatchEngineResultsAsAtomSet(long jarg1, mdGlobalAddr jarg1_, String jarg2);
  public final static native String mdGlobalAddr_OutputMappingResultsAsAtomSet(long jarg1, mdGlobalAddr jarg1_, String jarg2);
  public final static native void mdGlobalAddr_SetOutputsFromAtomSet(long jarg1, mdGlobalAddr jarg1_, String jarg2);
}
