/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.melissadata;

public class mdMUMatchcodeComponent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected mdMUMatchcodeComponent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(mdMUMatchcodeComponent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mdMatchUpJavaWrapperJNI.delete_mdMUMatchcodeComponent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI(SWIGTYPE_p_mdMUMatchcodeComponent_ value) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_I_set(swigCPtr, this, SWIGTYPE_p_mdMUMatchcodeComponent_.getCPtr(value));
  }

  public SWIGTYPE_p_mdMUMatchcodeComponent_ getI() {
    long cPtr = mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_I_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mdMUMatchcodeComponent_(cPtr, false);
  }

  public mdMUMatchcodeComponent() {
    this(mdMatchUpJavaWrapperJNI.new_mdMUMatchcodeComponent(), true);
  }

  public MatchcodeComponentType GetComponentType() {
    return MatchcodeComponentType.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetComponentType(swigCPtr, this));
  }

  public void SetComponentType(MatchcodeComponentType Type) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetComponentType(swigCPtr, this, Type.swigValue());
  }

  public int GetSize() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetSize(swigCPtr, this);
  }

  public void SetSize(int Size) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetSize(swigCPtr, this, Size);
  }

  public String GetLabel() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetLabel(swigCPtr, this);
  }

  public void SetLabel(String Label) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetLabel(swigCPtr, this, Label);
  }

  public int GetWordCount() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetWordCount(swigCPtr, this);
  }

  public void SetWordCount(int WordCount) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetWordCount(swigCPtr, this, WordCount);
  }

  public MatchcodeStart GetStart() {
    return MatchcodeStart.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetStart(swigCPtr, this));
  }

  public void SetStart(MatchcodeStart Start) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetStart(swigCPtr, this, Start.swigValue());
  }

  public int GetStartPos() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetStartPos(swigCPtr, this);
  }

  public void SetStartPos(int StartPos) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetStartPos(swigCPtr, this, StartPos);
  }

  public MatchcodeTrim GetTrim() {
    return MatchcodeTrim.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetTrim(swigCPtr, this));
  }

  public void SetTrim(MatchcodeTrim Trim) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetTrim(swigCPtr, this, Trim.swigValue());
  }

  public MatchcodeFuzzy GetFuzzy() {
    return MatchcodeFuzzy.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetFuzzy(swigCPtr, this));
  }

  public void SetFuzzy(MatchcodeFuzzy Fuzzy) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetFuzzy(swigCPtr, this, Fuzzy.swigValue());
  }

  public int GetNear() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetNear(swigCPtr, this);
  }

  public void SetNear(int Near) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetNear(swigCPtr, this, Near);
  }

  public double GetNearDbl() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetNearDbl(swigCPtr, this);
  }

  public void SetNearDbl(double Near) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetNearDbl(swigCPtr, this, Near);
  }

  public MatchcodeFieldMatch GetFieldMatch() {
    return MatchcodeFieldMatch.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetFieldMatch(swigCPtr, this));
  }

  public void SetFieldMatch(MatchcodeFieldMatch Match) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetFieldMatch(swigCPtr, this, Match.swigValue());
  }

  public MatchcodeSwap GetSwap() {
    return MatchcodeSwap.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetSwap(swigCPtr, this));
  }

  public void SetSwap(MatchcodeSwap Swap) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetSwap(swigCPtr, this, Swap.swigValue());
  }

  public MatchcodeCombination GetCombination() {
    return MatchcodeCombination.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetCombination(swigCPtr, this));
  }

  public void SetCombination(MatchcodeCombination Combination) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetCombination(swigCPtr, this, Combination.swigValue());
  }

  public ComponentCountryType GetComponentCountryTypeFromEnum(MatchcodeComponentType Value) {
    return ComponentCountryType.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetComponentCountryTypeFromEnum(swigCPtr, this, Value.swigValue()));
  }

  public String GetComponentDescription(int UseLabel) {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetComponentDescription(swigCPtr, this, UseLabel);
  }

  public String GetComponentDescriptionFromEnum(MatchcodeComponentType Value) {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetComponentDescriptionFromEnum(swigCPtr, this, Value.swigValue());
  }

  public String GetComponentAbbreviation() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetComponentAbbreviation(swigCPtr, this);
  }

  public MatchcodeComponentType ParseComponentDescription(String Value) {
    return MatchcodeComponentType.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ParseComponentDescription(swigCPtr, this, Value));
  }

  public String GetSizeDescription() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetSizeDescription(swigCPtr, this);
  }

  public int ParseSizeDescription(String Value) {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ParseSizeDescription(swigCPtr, this, Value);
  }

  public int ParseWordCountDescription(String Value) {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ParseWordCountDescription(swigCPtr, this, Value);
  }

  public String GetStartDescription() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetStartDescription(swigCPtr, this);
  }

  public MatchcodeStart ParseStartDescription(String Value) {
    return MatchcodeStart.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ParseStartDescription(swigCPtr, this, Value));
  }

  public int ParseStartPosDescription(String Value) {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ParseStartPosDescription(swigCPtr, this, Value);
  }

  public String GetFuzzyDescription(int Decorated) {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetFuzzyDescription(swigCPtr, this, Decorated);
  }

  public String GetFuzzyDescriptionFromEnum(MatchcodeFuzzy Value) {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetFuzzyDescriptionFromEnum(swigCPtr, this, Value.swigValue());
  }

  public MatchcodeFuzzy ParseFuzzyDescription(String Value) {
    return MatchcodeFuzzy.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ParseFuzzyDescription(swigCPtr, this, Value));
  }

  public double ParseNearDescription(String Value) {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ParseNearDescription(swigCPtr, this, Value);
  }

  public String GetFieldMatchDescription() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetFieldMatchDescription(swigCPtr, this);
  }

  public MatchcodeFieldMatch ParseFieldMatchDescription(String Value) {
    return MatchcodeFieldMatch.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ParseFieldMatchDescription(swigCPtr, this, Value));
  }

  public String GetSwapDescription() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetSwapDescription(swigCPtr, this);
  }

  public int CanChangeComponentType() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CanChangeComponentType(swigCPtr, this);
  }

  public int CanChangeLabel() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CanChangeLabel(swigCPtr, this);
  }

  public int CanChangeSize() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CanChangeSize(swigCPtr, this);
  }

  public int CanChangeWordCount() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CanChangeWordCount(swigCPtr, this);
  }

  public int CanChangeStart() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CanChangeStart(swigCPtr, this);
  }

  public int CanChangeTrim() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CanChangeTrim(swigCPtr, this);
  }

  public int CanChangeFuzzy() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CanChangeFuzzy(swigCPtr, this);
  }

  public int GetSizeMinimum() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetSizeMinimum(swigCPtr, this);
  }

  public int GetSizeMaximum() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetSizeMaximum(swigCPtr, this);
  }

  public MatchcodeStart GetAllowedStarts() {
    return MatchcodeStart.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetAllowedStarts(swigCPtr, this));
  }

  public MatchcodeFuzzy GetAllowedFuzzies() {
    return MatchcodeFuzzy.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetAllowedFuzzies(swigCPtr, this));
  }

  public int IsAllowedFuzzy(MatchcodeFuzzy Value) {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_IsAllowedFuzzy(swigCPtr, this, Value.swigValue());
  }

  public MatchcodeNearType GetFuzzyNearType() {
    return MatchcodeNearType.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetFuzzyNearType(swigCPtr, this));
  }

  public double GetNearMinimum() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetNearMinimum(swigCPtr, this);
  }

  public double GetNearMaximum() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetNearMaximum(swigCPtr, this);
  }

  public MatchcodeFieldMatch GetAllowedFieldMatches() {
    return MatchcodeFieldMatch.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetAllowedFieldMatches(swigCPtr, this));
  }

  public MatchcodeCombination GetAllowedCombinations() {
    return MatchcodeCombination.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetAllowedCombinations(swigCPtr, this));
  }

  public MatchcodeSwap GetAllowedSwaps() {
    return MatchcodeSwap.swigToEnum(mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetAllowedSwaps(swigCPtr, this));
  }

  public String GetComponentTypeEnum() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetComponentTypeEnum(swigCPtr, this);
  }

  public String GetFuzzyEnum() {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetFuzzyEnum(swigCPtr, this);
  }

  public void SetReserved(String Property, String Value) {
    mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SetReserved(swigCPtr, this, Property, Value);
  }

  public String GetReserved(String Property) {
    return mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GetReserved(swigCPtr, this, Property);
  }

  public final static class ProgramStatus {
    public final static ProgramStatus ErrorNone = new ProgramStatus("ErrorNone", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ErrorNone_get());
    public final static ProgramStatus ErrorConfigFile = new ProgramStatus("ErrorConfigFile");
    public final static ProgramStatus ErrorLicenseExpired = new ProgramStatus("ErrorLicenseExpired");
    public final static ProgramStatus ErrorDatabaseExpired = new ProgramStatus("ErrorDatabaseExpired");
    public final static ProgramStatus ErrorMatchcodeNotSpecified = new ProgramStatus("ErrorMatchcodeNotSpecified");
    public final static ProgramStatus ErrorMatchcodeNotFound = new ProgramStatus("ErrorMatchcodeNotFound");
    public final static ProgramStatus ErrorInvalidMatchcode = new ProgramStatus("ErrorInvalidMatchcode");
    public final static ProgramStatus ErrorKeyFile = new ProgramStatus("ErrorKeyFile");
    public final static ProgramStatus ErrorNoneIntersectingGroupCache = new ProgramStatus("ErrorNoneIntersectingGroupCache");
    public final static ProgramStatus ErrorMatchcodeObsolete = new ProgramStatus("ErrorMatchcodeObsolete");
    public final static ProgramStatus ErrorGlobalAddrInit = new ProgramStatus("ErrorGlobalAddrInit");
    public final static ProgramStatus ErrorIntlLicenseRequired = new ProgramStatus("ErrorIntlLicenseRequired");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static ProgramStatus swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + ProgramStatus.class + " with value " + swigValue);
    }

    private ProgramStatus(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private ProgramStatus(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private ProgramStatus(String swigName, ProgramStatus swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static ProgramStatus[] swigValues = { ErrorNone, ErrorConfigFile, ErrorLicenseExpired, ErrorDatabaseExpired, ErrorMatchcodeNotSpecified, ErrorMatchcodeNotFound, ErrorInvalidMatchcode, ErrorKeyFile, ErrorNoneIntersectingGroupCache, ErrorMatchcodeObsolete, ErrorGlobalAddrInit, ErrorIntlLicenseRequired };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class MatchcodeComponentType {
    public final static MatchcodeComponentType PrefixComp = new MatchcodeComponentType("PrefixComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_PrefixComp_get());
    public final static MatchcodeComponentType FirstComp = new MatchcodeComponentType("FirstComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_FirstComp_get());
    public final static MatchcodeComponentType MiddleComp = new MatchcodeComponentType("MiddleComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_MiddleComp_get());
    public final static MatchcodeComponentType LastComp = new MatchcodeComponentType("LastComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_LastComp_get());
    public final static MatchcodeComponentType SuffixComp = new MatchcodeComponentType("SuffixComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SuffixComp_get());
    public final static MatchcodeComponentType GenderComp = new MatchcodeComponentType("GenderComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GenderComp_get());
    public final static MatchcodeComponentType FirstNicknameComp = new MatchcodeComponentType("FirstNicknameComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_FirstNicknameComp_get());
    public final static MatchcodeComponentType MiddleNicknameComp = new MatchcodeComponentType("MiddleNicknameComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_MiddleNicknameComp_get());
    public final static MatchcodeComponentType TitleComp = new MatchcodeComponentType("TitleComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_TitleComp_get());
    public final static MatchcodeComponentType CompanyComp = new MatchcodeComponentType("CompanyComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CompanyComp_get());
    public final static MatchcodeComponentType CompanyAcronymComp = new MatchcodeComponentType("CompanyAcronymComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CompanyAcronymComp_get());
    public final static MatchcodeComponentType StreetNumberComp = new MatchcodeComponentType("StreetNumberComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_StreetNumberComp_get());
    public final static MatchcodeComponentType StreetPreDirComp = new MatchcodeComponentType("StreetPreDirComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_StreetPreDirComp_get());
    public final static MatchcodeComponentType StreetNameComp = new MatchcodeComponentType("StreetNameComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_StreetNameComp_get());
    public final static MatchcodeComponentType StreetSuffixComp = new MatchcodeComponentType("StreetSuffixComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_StreetSuffixComp_get());
    public final static MatchcodeComponentType StreetPostDirComp = new MatchcodeComponentType("StreetPostDirComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_StreetPostDirComp_get());
    public final static MatchcodeComponentType POBoxComp = new MatchcodeComponentType("POBoxComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_POBoxComp_get());
    public final static MatchcodeComponentType SecondaryComp = new MatchcodeComponentType("SecondaryComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SecondaryComp_get());
    public final static MatchcodeComponentType AddressComp = new MatchcodeComponentType("AddressComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_AddressComp_get());
    public final static MatchcodeComponentType CityComp = new MatchcodeComponentType("CityComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CityComp_get());
    public final static MatchcodeComponentType StateComp = new MatchcodeComponentType("StateComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_StateComp_get());
    public final static MatchcodeComponentType Zip9Comp = new MatchcodeComponentType("Zip9Comp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Zip9Comp_get());
    public final static MatchcodeComponentType Zip5Comp = new MatchcodeComponentType("Zip5Comp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Zip5Comp_get());
    public final static MatchcodeComponentType Zip4Comp = new MatchcodeComponentType("Zip4Comp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Zip4Comp_get());
    public final static MatchcodeComponentType CountryComp = new MatchcodeComponentType("CountryComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CountryComp_get());
    public final static MatchcodeComponentType CanadianPCComp = new MatchcodeComponentType("CanadianPCComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CanadianPCComp_get());
    public final static MatchcodeComponentType PhoneComp = new MatchcodeComponentType("PhoneComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_PhoneComp_get());
    public final static MatchcodeComponentType EMailComp = new MatchcodeComponentType("EMailComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_EMailComp_get());
    public final static MatchcodeComponentType CreditCardComp = new MatchcodeComponentType("CreditCardComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CreditCardComp_get());
    public final static MatchcodeComponentType GeneralComp = new MatchcodeComponentType("GeneralComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GeneralComp_get());
    public final static MatchcodeComponentType GeoDistanceComp = new MatchcodeComponentType("GeoDistanceComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GeoDistanceComp_get());
    public final static MatchcodeComponentType DateComp = new MatchcodeComponentType("DateComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_DateComp_get());
    public final static MatchcodeComponentType NumericComp = new MatchcodeComponentType("NumericComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_NumericComp_get());
    public final static MatchcodeComponentType PremisesNumberComp = new MatchcodeComponentType("PremisesNumberComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_PremisesNumberComp_get());
    public final static MatchcodeComponentType ThoroughfarePreDirComp = new MatchcodeComponentType("ThoroughfarePreDirComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ThoroughfarePreDirComp_get());
    public final static MatchcodeComponentType ThoroughfareLeadingTypeComp = new MatchcodeComponentType("ThoroughfareLeadingTypeComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ThoroughfareLeadingTypeComp_get());
    public final static MatchcodeComponentType ThoroughfareNameComp = new MatchcodeComponentType("ThoroughfareNameComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ThoroughfareNameComp_get());
    public final static MatchcodeComponentType ThoroughfarePostDirComp = new MatchcodeComponentType("ThoroughfarePostDirComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ThoroughfarePostDirComp_get());
    public final static MatchcodeComponentType ThoroughfareTrailingTypeComp = new MatchcodeComponentType("ThoroughfareTrailingTypeComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ThoroughfareTrailingTypeComp_get());
    public final static MatchcodeComponentType DepThoroughfarePreDirComp = new MatchcodeComponentType("DepThoroughfarePreDirComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_DepThoroughfarePreDirComp_get());
    public final static MatchcodeComponentType DepThoroughfareLeadingTypeComp = new MatchcodeComponentType("DepThoroughfareLeadingTypeComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_DepThoroughfareLeadingTypeComp_get());
    public final static MatchcodeComponentType DepThoroughfareNameComp = new MatchcodeComponentType("DepThoroughfareNameComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_DepThoroughfareNameComp_get());
    public final static MatchcodeComponentType DepThoroughfarePostDirComp = new MatchcodeComponentType("DepThoroughfarePostDirComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_DepThoroughfarePostDirComp_get());
    public final static MatchcodeComponentType DepThoroughfareTrailingTypeComp = new MatchcodeComponentType("DepThoroughfareTrailingTypeComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_DepThoroughfareTrailingTypeComp_get());
    public final static MatchcodeComponentType LocalityComp = new MatchcodeComponentType("LocalityComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_LocalityComp_get());
    public final static MatchcodeComponentType DependentLocalityComp = new MatchcodeComponentType("DependentLocalityComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_DependentLocalityComp_get());
    public final static MatchcodeComponentType DblDependentLocalityComp = new MatchcodeComponentType("DblDependentLocalityComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_DblDependentLocalityComp_get());
    public final static MatchcodeComponentType AdministrativeAreaComp = new MatchcodeComponentType("AdministrativeAreaComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_AdministrativeAreaComp_get());
    public final static MatchcodeComponentType SubAdministrativeAreaComp = new MatchcodeComponentType("SubAdministrativeAreaComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SubAdministrativeAreaComp_get());
    public final static MatchcodeComponentType PostalCodeComp = new MatchcodeComponentType("PostalCodeComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_PostalCodeComp_get());
    public final static MatchcodeComponentType SubNationalAreaComp = new MatchcodeComponentType("SubNationalAreaComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SubNationalAreaComp_get());
    public final static MatchcodeComponentType PostBoxComp = new MatchcodeComponentType("PostBoxComp", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_PostBoxComp_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static MatchcodeComponentType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + MatchcodeComponentType.class + " with value " + swigValue);
    }

    private MatchcodeComponentType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private MatchcodeComponentType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private MatchcodeComponentType(String swigName, MatchcodeComponentType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static MatchcodeComponentType[] swigValues = { PrefixComp, FirstComp, MiddleComp, LastComp, SuffixComp, GenderComp, FirstNicknameComp, MiddleNicknameComp, TitleComp, CompanyComp, CompanyAcronymComp, StreetNumberComp, StreetPreDirComp, StreetNameComp, StreetSuffixComp, StreetPostDirComp, POBoxComp, SecondaryComp, AddressComp, CityComp, StateComp, Zip9Comp, Zip5Comp, Zip4Comp, CountryComp, CanadianPCComp, PhoneComp, EMailComp, CreditCardComp, GeneralComp, GeoDistanceComp, DateComp, NumericComp, PremisesNumberComp, ThoroughfarePreDirComp, ThoroughfareLeadingTypeComp, ThoroughfareNameComp, ThoroughfarePostDirComp, ThoroughfareTrailingTypeComp, DepThoroughfarePreDirComp, DepThoroughfareLeadingTypeComp, DepThoroughfareNameComp, DepThoroughfarePostDirComp, DepThoroughfareTrailingTypeComp, LocalityComp, DependentLocalityComp, DblDependentLocalityComp, AdministrativeAreaComp, SubAdministrativeAreaComp, PostalCodeComp, SubNationalAreaComp, PostBoxComp };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class MatchcodeStart {
    public final static MatchcodeStart Left = new MatchcodeStart("Left", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Left_get());
    public final static MatchcodeStart Right = new MatchcodeStart("Right", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Right_get());
    public final static MatchcodeStart StartAtPos = new MatchcodeStart("StartAtPos", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_StartAtPos_get());
    public final static MatchcodeStart StartAtWord = new MatchcodeStart("StartAtWord", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_StartAtWord_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static MatchcodeStart swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + MatchcodeStart.class + " with value " + swigValue);
    }

    private MatchcodeStart(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private MatchcodeStart(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private MatchcodeStart(String swigName, MatchcodeStart swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static MatchcodeStart[] swigValues = { Left, Right, StartAtPos, StartAtWord };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class MatchcodeTrim {
    public final static MatchcodeTrim LeftTrim = new MatchcodeTrim("LeftTrim", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_LeftTrim_get());
    public final static MatchcodeTrim RightTrim = new MatchcodeTrim("RightTrim", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_RightTrim_get());
    public final static MatchcodeTrim AllTrim = new MatchcodeTrim("AllTrim", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_AllTrim_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static MatchcodeTrim swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + MatchcodeTrim.class + " with value " + swigValue);
    }

    private MatchcodeTrim(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private MatchcodeTrim(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private MatchcodeTrim(String swigName, MatchcodeTrim swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static MatchcodeTrim[] swigValues = { LeftTrim, RightTrim, AllTrim };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class MatchcodeFuzzy {
    public final static MatchcodeFuzzy Exact = new MatchcodeFuzzy("Exact", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Exact_get());
    public final static MatchcodeFuzzy SoundEx = new MatchcodeFuzzy("SoundEx", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SoundEx_get());
    public final static MatchcodeFuzzy Phonetex = new MatchcodeFuzzy("Phonetex", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Phonetex_get());
    public final static MatchcodeFuzzy Containment = new MatchcodeFuzzy("Containment", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Containment_get());
    public final static MatchcodeFuzzy Frequency = new MatchcodeFuzzy("Frequency", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Frequency_get());
    public final static MatchcodeFuzzy FastNear = new MatchcodeFuzzy("FastNear", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_FastNear_get());
    public final static MatchcodeFuzzy AccurateNear = new MatchcodeFuzzy("AccurateNear", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_AccurateNear_get());
    public final static MatchcodeFuzzy VowelsOnly = new MatchcodeFuzzy("VowelsOnly", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_VowelsOnly_get());
    public final static MatchcodeFuzzy ConsonantsOnly = new MatchcodeFuzzy("ConsonantsOnly", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_ConsonantsOnly_get());
    public final static MatchcodeFuzzy AlphasOnly = new MatchcodeFuzzy("AlphasOnly", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_AlphasOnly_get());
    public final static MatchcodeFuzzy NumericsOnly = new MatchcodeFuzzy("NumericsOnly", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_NumericsOnly_get());
    public final static MatchcodeFuzzy FrequencyNear = new MatchcodeFuzzy("FrequencyNear", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_FrequencyNear_get());
    public final static MatchcodeFuzzy NGram = new MatchcodeFuzzy("NGram", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_NGram_get());
    public final static MatchcodeFuzzy Jaro = new MatchcodeFuzzy("Jaro", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Jaro_get());
    public final static MatchcodeFuzzy JaroWinkler = new MatchcodeFuzzy("JaroWinkler", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_JaroWinkler_get());
    public final static MatchcodeFuzzy LCS = new MatchcodeFuzzy("LCS", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_LCS_get());
    public final static MatchcodeFuzzy NeedlemanWunsch = new MatchcodeFuzzy("NeedlemanWunsch", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_NeedlemanWunsch_get());
    public final static MatchcodeFuzzy MDKeyboard = new MatchcodeFuzzy("MDKeyboard", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_MDKeyboard_get());
    public final static MatchcodeFuzzy SmithWatermanGotoh = new MatchcodeFuzzy("SmithWatermanGotoh", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SmithWatermanGotoh_get());
    public final static MatchcodeFuzzy Dice = new MatchcodeFuzzy("Dice", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Dice_get());
    public final static MatchcodeFuzzy Jaccard = new MatchcodeFuzzy("Jaccard", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Jaccard_get());
    public final static MatchcodeFuzzy Overlap = new MatchcodeFuzzy("Overlap", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Overlap_get());
    public final static MatchcodeFuzzy DoubleMetaphone = new MatchcodeFuzzy("DoubleMetaphone", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_DoubleMetaphone_get());
    public final static MatchcodeFuzzy UTF8Near = new MatchcodeFuzzy("UTF8Near", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_UTF8Near_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static MatchcodeFuzzy swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + MatchcodeFuzzy.class + " with value " + swigValue);
    }

    private MatchcodeFuzzy(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private MatchcodeFuzzy(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private MatchcodeFuzzy(String swigName, MatchcodeFuzzy swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static MatchcodeFuzzy[] swigValues = { Exact, SoundEx, Phonetex, Containment, Frequency, FastNear, AccurateNear, VowelsOnly, ConsonantsOnly, AlphasOnly, NumericsOnly, FrequencyNear, NGram, Jaro, JaroWinkler, LCS, NeedlemanWunsch, MDKeyboard, SmithWatermanGotoh, Dice, Jaccard, Overlap, DoubleMetaphone, UTF8Near };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class MatchcodeFieldMatch {
    public final static MatchcodeFieldMatch NoFieldMatch = new MatchcodeFieldMatch("NoFieldMatch", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_NoFieldMatch_get());
    public final static MatchcodeFieldMatch BothBlankMatch = new MatchcodeFieldMatch("BothBlankMatch", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_BothBlankMatch_get());
    public final static MatchcodeFieldMatch OneBlankMatch = new MatchcodeFieldMatch("OneBlankMatch", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_OneBlankMatch_get());
    public final static MatchcodeFieldMatch InitialMatch = new MatchcodeFieldMatch("InitialMatch", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_InitialMatch_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static MatchcodeFieldMatch swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + MatchcodeFieldMatch.class + " with value " + swigValue);
    }

    private MatchcodeFieldMatch(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private MatchcodeFieldMatch(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private MatchcodeFieldMatch(String swigName, MatchcodeFieldMatch swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static MatchcodeFieldMatch[] swigValues = { NoFieldMatch, BothBlankMatch, OneBlankMatch, InitialMatch };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class MatchcodeSwap {
    public final static MatchcodeSwap NoSwap = new MatchcodeSwap("NoSwap", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_NoSwap_get());
    public final static MatchcodeSwap SwapA = new MatchcodeSwap("SwapA", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SwapA_get());
    public final static MatchcodeSwap SwapB = new MatchcodeSwap("SwapB", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SwapB_get());
    public final static MatchcodeSwap SwapC = new MatchcodeSwap("SwapC", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SwapC_get());
    public final static MatchcodeSwap SwapD = new MatchcodeSwap("SwapD", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SwapD_get());
    public final static MatchcodeSwap SwapE = new MatchcodeSwap("SwapE", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SwapE_get());
    public final static MatchcodeSwap SwapF = new MatchcodeSwap("SwapF", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SwapF_get());
    public final static MatchcodeSwap SwapG = new MatchcodeSwap("SwapG", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SwapG_get());
    public final static MatchcodeSwap SwapH = new MatchcodeSwap("SwapH", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SwapH_get());
    public final static MatchcodeSwap BothA = new MatchcodeSwap("BothA", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_BothA_get());
    public final static MatchcodeSwap BothB = new MatchcodeSwap("BothB", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_BothB_get());
    public final static MatchcodeSwap BothC = new MatchcodeSwap("BothC", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_BothC_get());
    public final static MatchcodeSwap BothD = new MatchcodeSwap("BothD", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_BothD_get());
    public final static MatchcodeSwap BothE = new MatchcodeSwap("BothE", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_BothE_get());
    public final static MatchcodeSwap BothF = new MatchcodeSwap("BothF", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_BothF_get());
    public final static MatchcodeSwap BothG = new MatchcodeSwap("BothG", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_BothG_get());
    public final static MatchcodeSwap BothH = new MatchcodeSwap("BothH", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_BothH_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static MatchcodeSwap swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + MatchcodeSwap.class + " with value " + swigValue);
    }

    private MatchcodeSwap(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private MatchcodeSwap(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private MatchcodeSwap(String swigName, MatchcodeSwap swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static MatchcodeSwap[] swigValues = { NoSwap, SwapA, SwapB, SwapC, SwapD, SwapE, SwapF, SwapG, SwapH, BothA, BothB, BothC, BothD, BothE, BothF, BothG, BothH };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class MatchcodeCombination {
    public final static MatchcodeCombination Combo1 = new MatchcodeCombination("Combo1", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo1_get());
    public final static MatchcodeCombination Combo2 = new MatchcodeCombination("Combo2", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo2_get());
    public final static MatchcodeCombination Combo3 = new MatchcodeCombination("Combo3", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo3_get());
    public final static MatchcodeCombination Combo4 = new MatchcodeCombination("Combo4", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo4_get());
    public final static MatchcodeCombination Combo5 = new MatchcodeCombination("Combo5", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo5_get());
    public final static MatchcodeCombination Combo6 = new MatchcodeCombination("Combo6", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo6_get());
    public final static MatchcodeCombination Combo7 = new MatchcodeCombination("Combo7", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo7_get());
    public final static MatchcodeCombination Combo8 = new MatchcodeCombination("Combo8", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo8_get());
    public final static MatchcodeCombination Combo9 = new MatchcodeCombination("Combo9", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo9_get());
    public final static MatchcodeCombination Combo10 = new MatchcodeCombination("Combo10", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo10_get());
    public final static MatchcodeCombination Combo11 = new MatchcodeCombination("Combo11", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo11_get());
    public final static MatchcodeCombination Combo12 = new MatchcodeCombination("Combo12", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo12_get());
    public final static MatchcodeCombination Combo13 = new MatchcodeCombination("Combo13", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo13_get());
    public final static MatchcodeCombination Combo14 = new MatchcodeCombination("Combo14", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo14_get());
    public final static MatchcodeCombination Combo15 = new MatchcodeCombination("Combo15", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo15_get());
    public final static MatchcodeCombination Combo16 = new MatchcodeCombination("Combo16", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Combo16_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static MatchcodeCombination swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + MatchcodeCombination.class + " with value " + swigValue);
    }

    private MatchcodeCombination(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private MatchcodeCombination(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private MatchcodeCombination(String swigName, MatchcodeCombination swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static MatchcodeCombination[] swigValues = { Combo1, Combo2, Combo3, Combo4, Combo5, Combo6, Combo7, Combo8, Combo9, Combo10, Combo11, Combo12, Combo13, Combo14, Combo15, Combo16 };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class MatchcodeMappingTarget {
    public final static MatchcodeMappingTarget PrefixType = new MatchcodeMappingTarget("PrefixType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_PrefixType_get());
    public final static MatchcodeMappingTarget FirstType = new MatchcodeMappingTarget("FirstType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_FirstType_get());
    public final static MatchcodeMappingTarget MiddleType = new MatchcodeMappingTarget("MiddleType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_MiddleType_get());
    public final static MatchcodeMappingTarget LastType = new MatchcodeMappingTarget("LastType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_LastType_get());
    public final static MatchcodeMappingTarget SuffixType = new MatchcodeMappingTarget("SuffixType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_SuffixType_get());
    public final static MatchcodeMappingTarget GenderType = new MatchcodeMappingTarget("GenderType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GenderType_get());
    public final static MatchcodeMappingTarget FirstNicknameType = new MatchcodeMappingTarget("FirstNicknameType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_FirstNicknameType_get());
    public final static MatchcodeMappingTarget MiddleNicknameType = new MatchcodeMappingTarget("MiddleNicknameType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_MiddleNicknameType_get());
    public final static MatchcodeMappingTarget TitleType = new MatchcodeMappingTarget("TitleType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_TitleType_get());
    public final static MatchcodeMappingTarget CompanyType = new MatchcodeMappingTarget("CompanyType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CompanyType_get());
    public final static MatchcodeMappingTarget CompanyAcronymType = new MatchcodeMappingTarget("CompanyAcronymType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CompanyAcronymType_get());
    public final static MatchcodeMappingTarget AddressType = new MatchcodeMappingTarget("AddressType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_AddressType_get());
    public final static MatchcodeMappingTarget CityType = new MatchcodeMappingTarget("CityType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CityType_get());
    public final static MatchcodeMappingTarget StateType = new MatchcodeMappingTarget("StateType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_StateType_get());
    public final static MatchcodeMappingTarget Zip9Type = new MatchcodeMappingTarget("Zip9Type", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Zip9Type_get());
    public final static MatchcodeMappingTarget Zip5Type = new MatchcodeMappingTarget("Zip5Type", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Zip5Type_get());
    public final static MatchcodeMappingTarget Zip4Type = new MatchcodeMappingTarget("Zip4Type", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Zip4Type_get());
    public final static MatchcodeMappingTarget CountryType = new MatchcodeMappingTarget("CountryType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CountryType_get());
    public final static MatchcodeMappingTarget CanadianPCType = new MatchcodeMappingTarget("CanadianPCType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CanadianPCType_get());
    public final static MatchcodeMappingTarget PhoneType = new MatchcodeMappingTarget("PhoneType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_PhoneType_get());
    public final static MatchcodeMappingTarget EMailType = new MatchcodeMappingTarget("EMailType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_EMailType_get());
    public final static MatchcodeMappingTarget CreditCardType = new MatchcodeMappingTarget("CreditCardType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CreditCardType_get());
    public final static MatchcodeMappingTarget GeneralType = new MatchcodeMappingTarget("GeneralType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GeneralType_get());
    public final static MatchcodeMappingTarget Address1Type = new MatchcodeMappingTarget("Address1Type", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Address1Type_get());
    public final static MatchcodeMappingTarget Address2Type = new MatchcodeMappingTarget("Address2Type", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Address2Type_get());
    public final static MatchcodeMappingTarget Address3Type = new MatchcodeMappingTarget("Address3Type", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Address3Type_get());
    public final static MatchcodeMappingTarget LatitudeType = new MatchcodeMappingTarget("LatitudeType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_LatitudeType_get());
    public final static MatchcodeMappingTarget LongitudeType = new MatchcodeMappingTarget("LongitudeType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_LongitudeType_get());
    public final static MatchcodeMappingTarget DateType = new MatchcodeMappingTarget("DateType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_DateType_get());
    public final static MatchcodeMappingTarget NumericType = new MatchcodeMappingTarget("NumericType", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_NumericType_get());
    public final static MatchcodeMappingTarget Address4Type = new MatchcodeMappingTarget("Address4Type", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Address4Type_get());
    public final static MatchcodeMappingTarget Address5Type = new MatchcodeMappingTarget("Address5Type", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Address5Type_get());
    public final static MatchcodeMappingTarget Address6Type = new MatchcodeMappingTarget("Address6Type", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Address6Type_get());
    public final static MatchcodeMappingTarget Address7Type = new MatchcodeMappingTarget("Address7Type", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Address7Type_get());
    public final static MatchcodeMappingTarget Address8Type = new MatchcodeMappingTarget("Address8Type", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Address8Type_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static MatchcodeMappingTarget swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + MatchcodeMappingTarget.class + " with value " + swigValue);
    }

    private MatchcodeMappingTarget(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private MatchcodeMappingTarget(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private MatchcodeMappingTarget(String swigName, MatchcodeMappingTarget swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static MatchcodeMappingTarget[] swigValues = { PrefixType, FirstType, MiddleType, LastType, SuffixType, GenderType, FirstNicknameType, MiddleNicknameType, TitleType, CompanyType, CompanyAcronymType, AddressType, CityType, StateType, Zip9Type, Zip5Type, Zip4Type, CountryType, CanadianPCType, PhoneType, EMailType, CreditCardType, GeneralType, Address1Type, Address2Type, Address3Type, LatitudeType, LongitudeType, DateType, NumericType, Address4Type, Address5Type, Address6Type, Address7Type, Address8Type };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class MatchcodeStatus {
    public final static MatchcodeStatus MCNoError = new MatchcodeStatus("MCNoError", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_MCNoError_get());
    public final static MatchcodeStatus MCFirstComponentFuzzyOptions = new MatchcodeStatus("MCFirstComponentFuzzyOptions");
    public final static MatchcodeStatus MCFirstComponentNoSwapPair = new MatchcodeStatus("MCFirstComponentNoSwapPair");
    public final static MatchcodeStatus MCDataTypeNoFuzzy = new MatchcodeStatus("MCDataTypeNoFuzzy");
    public final static MatchcodeStatus MCComponentFuzzyIncorrectSize = new MatchcodeStatus("MCComponentFuzzyIncorrectSize");
    public final static MatchcodeStatus MCDataTypeNoMaximumNumberWords = new MatchcodeStatus("MCDataTypeNoMaximumNumberWords");
    public final static MatchcodeStatus MCDataTypeNoStartRightOrWordOrPos = new MatchcodeStatus("MCDataTypeNoStartRightOrWordOrPos");
    public final static MatchcodeStatus MCIncorrectMaximumNumberWords = new MatchcodeStatus("MCIncorrectMaximumNumberWords");
    public final static MatchcodeStatus MCNearOutOfRange = new MatchcodeStatus("MCNearOutOfRange");
    public final static MatchcodeStatus MCFirstComponentNotUsedInEveryCondition = new MatchcodeStatus("MCFirstComponentNotUsedInEveryCondition");
    public final static MatchcodeStatus MCCannotChangeFirstComponent = new MatchcodeStatus("MCCannotChangeFirstComponent");
    public final static MatchcodeStatus MCInvalidSwapPair = new MatchcodeStatus("MCInvalidSwapPair");
    public final static MatchcodeStatus MCIncorrectStartPosOrStartWord = new MatchcodeStatus("MCIncorrectStartPosOrStartWord");
    public final static MatchcodeStatus MCInvalidMatchcodeComponentType = new MatchcodeStatus("MCInvalidMatchcodeComponentType");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static MatchcodeStatus swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + MatchcodeStatus.class + " with value " + swigValue);
    }

    private MatchcodeStatus(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private MatchcodeStatus(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private MatchcodeStatus(String swigName, MatchcodeStatus swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static MatchcodeStatus[] swigValues = { MCNoError, MCFirstComponentFuzzyOptions, MCFirstComponentNoSwapPair, MCDataTypeNoFuzzy, MCComponentFuzzyIncorrectSize, MCDataTypeNoMaximumNumberWords, MCDataTypeNoStartRightOrWordOrPos, MCIncorrectMaximumNumberWords, MCNearOutOfRange, MCFirstComponentNotUsedInEveryCondition, MCCannotChangeFirstComponent, MCInvalidSwapPair, MCIncorrectStartPosOrStartWord, MCInvalidMatchcodeComponentType };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class MatchcodeMapping {
    public final static MatchcodeMapping Prefix = new MatchcodeMapping("Prefix", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Prefix_get());
    public final static MatchcodeMapping Gender = new MatchcodeMapping("Gender", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Gender_get());
    public final static MatchcodeMapping First = new MatchcodeMapping("First", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_First_get());
    public final static MatchcodeMapping MixedFirst = new MatchcodeMapping("MixedFirst", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_MixedFirst_get());
    public final static MatchcodeMapping Middle = new MatchcodeMapping("Middle", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Middle_get());
    public final static MatchcodeMapping Last = new MatchcodeMapping("Last", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Last_get());
    public final static MatchcodeMapping MixedLast = new MatchcodeMapping("MixedLast", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_MixedLast_get());
    public final static MatchcodeMapping Suffix = new MatchcodeMapping("Suffix", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Suffix_get());
    public final static MatchcodeMapping FullName = new MatchcodeMapping("FullName", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_FullName_get());
    public final static MatchcodeMapping InverseName = new MatchcodeMapping("InverseName", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_InverseName_get());
    public final static MatchcodeMapping GovernmentInverseName = new MatchcodeMapping("GovernmentInverseName", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_GovernmentInverseName_get());
    public final static MatchcodeMapping Title = new MatchcodeMapping("Title", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Title_get());
    public final static MatchcodeMapping Company = new MatchcodeMapping("Company", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Company_get());
    public final static MatchcodeMapping Address = new MatchcodeMapping("Address", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Address_get());
    public final static MatchcodeMapping City = new MatchcodeMapping("City", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_City_get());
    public final static MatchcodeMapping State = new MatchcodeMapping("State", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_State_get());
    public final static MatchcodeMapping Zip9 = new MatchcodeMapping("Zip9", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Zip9_get());
    public final static MatchcodeMapping Zip5 = new MatchcodeMapping("Zip5", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Zip5_get());
    public final static MatchcodeMapping Zip4 = new MatchcodeMapping("Zip4", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Zip4_get());
    public final static MatchcodeMapping CityStZip = new MatchcodeMapping("CityStZip", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CityStZip_get());
    public final static MatchcodeMapping Country = new MatchcodeMapping("Country", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Country_get());
    public final static MatchcodeMapping CanadianPostalCode = new MatchcodeMapping("CanadianPostalCode", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CanadianPostalCode_get());
    public final static MatchcodeMapping Phone = new MatchcodeMapping("Phone", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Phone_get());
    public final static MatchcodeMapping EMail = new MatchcodeMapping("EMail", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_EMail_get());
    public final static MatchcodeMapping CreditCard = new MatchcodeMapping("CreditCard", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_CreditCard_get());
    public final static MatchcodeMapping General = new MatchcodeMapping("General", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_General_get());
    public final static MatchcodeMapping Latitude = new MatchcodeMapping("Latitude", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Latitude_get());
    public final static MatchcodeMapping Longitude = new MatchcodeMapping("Longitude", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Longitude_get());
    public final static MatchcodeMapping Date = new MatchcodeMapping("Date", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Date_get());
    public final static MatchcodeMapping Numeric = new MatchcodeMapping("Numeric", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Numeric_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static MatchcodeMapping swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + MatchcodeMapping.class + " with value " + swigValue);
    }

    private MatchcodeMapping(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private MatchcodeMapping(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private MatchcodeMapping(String swigName, MatchcodeMapping swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static MatchcodeMapping[] swigValues = { Prefix, Gender, First, MixedFirst, Middle, Last, MixedLast, Suffix, FullName, InverseName, GovernmentInverseName, Title, Company, Address, City, State, Zip9, Zip5, Zip4, CityStZip, Country, CanadianPostalCode, Phone, EMail, CreditCard, General, Latitude, Longitude, Date, Numeric };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class MatchcodeNearType {
    public final static MatchcodeNearType NearNone = new MatchcodeNearType("NearNone", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_NearNone_get());
    public final static MatchcodeNearType NearInteger = new MatchcodeNearType("NearInteger");
    public final static MatchcodeNearType NearFloat = new MatchcodeNearType("NearFloat");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static MatchcodeNearType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + MatchcodeNearType.class + " with value " + swigValue);
    }

    private MatchcodeNearType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private MatchcodeNearType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private MatchcodeNearType(String swigName, MatchcodeNearType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static MatchcodeNearType[] swigValues = { NearNone, NearInteger, NearFloat };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class ComponentCountryType {
    public final static ComponentCountryType US = new ComponentCountryType("US", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_US_get());
    public final static ComponentCountryType Canada = new ComponentCountryType("Canada", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Canada_get());
    public final static ComponentCountryType Global = new ComponentCountryType("Global", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Global_get());
    public final static ComponentCountryType Domestic = new ComponentCountryType("Domestic", mdMatchUpJavaWrapperJNI.mdMUMatchcodeComponent_Domestic_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static ComponentCountryType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + ComponentCountryType.class + " with value " + swigValue);
    }

    private ComponentCountryType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private ComponentCountryType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private ComponentCountryType(String swigName, ComponentCountryType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static ComponentCountryType[] swigValues = { US, Canada, Global, Domestic };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
