/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.melissadata;

public class mdNameJavaWrapperJNI {
//static{
//  try{ System.loadLibrary("mdNameJavaWrapper");}
//  catch(UnsatisfiedLinkError ule){
//    System.out.println(ule);
//    System.out.println("java.library.path = " + System.getProperty("java.library.path"));}}
  public final static native int mdName_NoError_get();
  public final static native int mdName_DefinitelyFull_get();
  public final static native int mdName_Male_get();
  public final static native int mdName_Aggressive_get();
  public final static native int mdName_Formal_get();
  public final static native int mdName_ParseLogic_get();
  public final static native int mdName_ResultCodeDescriptionLong_get();
  public final static native int mdName_ResultCodeDescriptionShort_get();
  public final static native long new_mdName();
  public final static native void delete_mdName(long jarg1);
  public final static native void mdName_SetPathToNameFiles(long jarg1, mdName jarg1_, String jarg2);
  public final static native int mdName_InitializeDataFiles(long jarg1, mdName jarg1_);
  public final static native String mdName_GetInitializeErrorString(long jarg1, mdName jarg1_);
  public final static native int mdName_SetLicenseString(long jarg1, mdName jarg1_, String jarg2);
  public final static native String mdName_GetBuildNumber(long jarg1, mdName jarg1_);
  public final static native String mdName_GetDatabaseDate(long jarg1, mdName jarg1_);
  public final static native String mdName_GetDatabaseExpirationDate(long jarg1, mdName jarg1_);
  public final static native String mdName_GetLicenseExpirationDate(long jarg1, mdName jarg1_);
  public final static native int mdName_SetPrimaryNameHint(long jarg1, mdName jarg1_, int jarg2);
  public final static native int mdName_SetSecondaryNameHint(long jarg1, mdName jarg1_, int jarg2);
  public final static native int mdName_SetFirstNameSpellingCorrection(long jarg1, mdName jarg1_, int jarg2);
  public final static native int mdName_SetMiddleNameLogic(long jarg1, mdName jarg1_, int jarg2);
  public final static native int mdName_SetGenderPopulation(long jarg1, mdName jarg1_, int jarg2);
  public final static native int mdName_SetGenderAggression(long jarg1, mdName jarg1_, int jarg2);
  public final static native int mdName_AddSalutation(long jarg1, mdName jarg1_, int jarg2);
  public final static native void mdName_SetSalutationPrefix(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_SetSalutationSuffix(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_SetSalutationSlug(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_ClearProperties(long jarg1, mdName jarg1_);
  public final static native void mdName_SetFullName(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_SetPrefix(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_SetPrefix2(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_SetFirstName(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_SetFirstName2(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_SetMiddleName(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_SetMiddleName2(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_SetSuffix(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_SetSuffix2(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_SetLastName(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_SetLastName2(long jarg1, mdName jarg1_, String jarg2);
  public final static native int mdName_Parse(long jarg1, mdName jarg1_);
  public final static native int mdName_Genderize(long jarg1, mdName jarg1_);
  public final static native int mdName_Salutate(long jarg1, mdName jarg1_);
  public final static native String mdName_GetStatusCode(long jarg1, mdName jarg1_);
  public final static native String mdName_GetErrorCode(long jarg1, mdName jarg1_);
  public final static native String mdName_GetChangeCode(long jarg1, mdName jarg1_);
  public final static native String mdName_GetDebugInfo(long jarg1, mdName jarg1_, String jarg2);
  public final static native String mdName_GetResults(long jarg1, mdName jarg1_);
  public final static native String mdName_GetResultCodeDescription(long jarg1, mdName jarg1_, String jarg2, int jarg3);
  public final static native String mdName_GetPrefix(long jarg1, mdName jarg1_);
  public final static native String mdName_GetPrefix2(long jarg1, mdName jarg1_);
  public final static native String mdName_GetFirstName(long jarg1, mdName jarg1_);
  public final static native String mdName_GetFirstName2(long jarg1, mdName jarg1_);
  public final static native String mdName_GetMiddleName(long jarg1, mdName jarg1_);
  public final static native String mdName_GetMiddleName2(long jarg1, mdName jarg1_);
  public final static native String mdName_GetLastName(long jarg1, mdName jarg1_);
  public final static native String mdName_GetLastName2(long jarg1, mdName jarg1_);
  public final static native String mdName_GetSuffix(long jarg1, mdName jarg1_);
  public final static native String mdName_GetSuffix2(long jarg1, mdName jarg1_);
  public final static native String mdName_GetGender(long jarg1, mdName jarg1_);
  public final static native String mdName_GetGender2(long jarg1, mdName jarg1_);
  public final static native String mdName_GetSalutation(long jarg1, mdName jarg1_);
  public final static native String mdName_StandardizeCompany(long jarg1, mdName jarg1_, String jarg2);
  public final static native void mdName_SetReserved(long jarg1, mdName jarg1_, String jarg2, String jarg3);
  public final static native String mdName_GetReserved(long jarg1, mdName jarg1_, String jarg2);
}
